In [1]:
str ='hi i am priyanka'
print(str.title())

Hi I Am Priyanka


In [2]:
map={}
for i in str:
    map[i]=map.get(i,0)+1
print(map)

{'h': 1, 'i': 3, ' ': 3, 'a': 3, 'm': 1, 'p': 1, 'r': 1, 'y': 1, 'n': 1, 'k': 1}


In [3]:
dict = {
  "state1":"cap1",
  "state2":"cap2",
  "state3":"cap3",
  "state4":"cap4",
 }
dict["state5"]="cap5"
print(dict)


{'state1': 'cap1', 'state2': 'cap2', 'state3': 'cap3', 'state4': 'cap4', 'state5': 'cap5'}


In [4]:
def countCharacterType(str):
     vowels = 0
     consonant = 0
     specialChar = 0
     digit = 0

     for i in range(0, len(str)):
         
         ch = str[i]
 
         if ( (ch >= 'a' and ch <= 'z') or
              (ch >= 'A' and ch <= 'Z') ):
 
             ch = ch.lower()
 
             if (ch == 'a' or ch == 'e' or ch == 'i'
                         or ch == 'o' or ch == 'u'):
                 vowels += 1
             else:
                 consonant += 1
         
         elif (ch >= '0' and ch <= '9'):
             digit += 1
         else:
             specialChar += 1
     
     print("Vowels:", vowels)
     print("Consonant:", consonant)
     print("Digit:", digit)
     print("Special Character:", specialChar)
str1 = "Password23@#"
countCharacterType(str1)

Vowels: 2
Consonant: 6
Digit: 2
Special Character: 2


In [1]:
str = input("Enter a string with less then 15 letter: ")
if(len(str)>15):
     print("Enter a string with less characters")
else:
     for i in range(len(str)):
         print(i,":",str[i])


0 : ,
1 : e
2 : m
3 : n
4 : f
5 : w
6 : l
7 : e
8 : j
9 : f
10 : j
11 : w
12 : k
13 : e


In [6]:
import numpy as np
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [9]:
arr = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                    ])
print(arr)
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
True


In [10]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])

res = np.dot(mat1,mat2)
print(res)
res = np.add(mat1,mat2)
print(res)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
[[ 4 10 11]
 [ 8 10 15]
 [ 8 68 10]]


In [11]:
arr = np.array([1,1,1,2,3,])
print(np.bincount(arr).argmax())

1


In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr = arr.flatten()
print(arr)

[1 2 3 4 5 6 7 8]
